/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unicordoba.registro.principal;

import unicordoba.registro.comandos.ICommand;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import unicordoba.registro.comandos.prueba.ComandoDinamizador;
import unicordoba.registro.comandos.prueba.ComandoEstudiante;
import unicordoba.registro.comandos.prueba.ComandoProfesor;

import unicordoba.registro.comandos.prueba.ComandoUtencilio;


/**import unicordoba.registro.ventana.prueba.ConsultaRegistroEstudiante;
import unicordoba.registro.ventana.prueba.FormularioRegistrarEstudiante;


 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        menuBar = new javax.swing.JMenuBar();
        utencilioMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        profesorMenu = new javax.swing.JMenu();
        profesorMenuItem = new javax.swing.JMenuItem();
        estudianteMenu = new javax.swing.JMenu();
        EstudianteMenuItem = new javax.swing.JMenuItem();
        dinamizadorMenu = new javax.swing.JMenu();
        dinamizadorMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        registrarasistenciaMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("R&C - Registro y Control");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        utencilioMenu.setMnemonic('u');
        utencilioMenu.setText("Utencilios");
        utencilioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utencilioMenuActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Utencilio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        utencilioMenu.add(jMenuItem1);

        menuBar.add(utencilioMenu);

        profesorMenu.setText("Profesor");

        profesorMenuItem.setText("Profesor");
        profesorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesorMenuItemActionPerformed(evt);
            }
        });
        profesorMenu.add(profesorMenuItem);

        menuBar.add(profesorMenu);

        estudianteMenu.setText("Estudiante");

        EstudianteMenuItem.setText("Estudiante");
        EstudianteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteMenuItemActionPerformed(evt);
            }
        });
        estudianteMenu.add(EstudianteMenuItem);

        menuBar.add(estudianteMenu);

        dinamizadorMenu.setText("Dinamizador");

        dinamizadorMenuItem.setText("Dinamizador");
        dinamizadorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinamizadorMenuItemActionPerformed(evt);
            }
        });
        dinamizadorMenu.add(dinamizadorMenuItem);

        menuBar.add(dinamizadorMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        registrarasistenciaMenu.setText("Registrar Asistencia");
        registrarasistenciaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarasistenciaMenuActionPerformed(evt);
            }
        });

        jMenuItem2.setText("registrarasistenciaMenuItem");
        registrarasistenciaMenu.add(jMenuItem2);

        menuBar.add(registrarasistenciaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JOptionPane.showMessageDialog(this, "Iniciando la aplicación");


    }//GEN-LAST:event_formWindowOpened

    private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMenuActionPerformed

    private void utencilioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utencilioMenuActionPerformed
       
    }//GEN-LAST:event_utencilioMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ICommand command = new ComandoUtencilio();
        command.execute();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void profesorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesorMenuItemActionPerformed
        ICommand command = new ComandoProfesor();
        command.execute();
    }//GEN-LAST:event_profesorMenuItemActionPerformed

    private void EstudianteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteMenuItemActionPerformed
        ICommand command = new ComandoEstudiante();
        command.execute();
    }//GEN-LAST:event_EstudianteMenuItemActionPerformed

    private void dinamizadorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinamizadorMenuItemActionPerformed
        ICommand command = new ComandoDinamizador();
        command.execute();
    }//GEN-LAST:event_dinamizadorMenuItemActionPerformed

    private void registrarasistenciaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarasistenciaMenuActionPerformed
        JOptionPane.showMessageDialog(null, "jajajaja te toco hacerlo David");
        JOptionPane.showMessageDialog(this, "Operación realizada correctamente");
    }//GEN-LAST:event_registrarasistenciaMenuActionPerformed

    private static Principal principal = null;

    public void AddVentana(JInternalFrame internalFrame) {
        desktopPane.add(internalFrame);
        internalFrame.setVisible(true);
    }
    

    public static Principal getSingleton() {
        if (principal == null) {
            principal = new Principal();
        }
        return principal;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                getSingleton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EstudianteMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu dinamizadorMenu;
    private javax.swing.JMenuItem dinamizadorMenuItem;
    private javax.swing.JMenu estudianteMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu profesorMenu;
    private javax.swing.JMenuItem profesorMenuItem;
    private javax.swing.JMenu registrarasistenciaMenu;
    private javax.swing.JMenu utencilioMenu;
    // End of variables declaration//GEN-END:variables

   

    

}
